apiVersion: v1
kind: Service
metadata:
  name: preference
  labels:
    app: preference
spec:
  type: NodePort  # use NodePort as type here
  ports:
  - name: http
    port: 8080
  selector:
    app: preference
