apiVersion: v1
kind: Service
metadata:
  name: recommendation
  labels:
    app: recommendation
spec:
  type: NodePort  # use NodePort as type here
  ports:
  - name: http
    port: 8080
  selector:
    app: recommendation
