apiVersion: batch/v1
kind: Job
metadata:
  name: spring-boot-crac-job
  namespace: crac
spec:
  template:
    spec:
      containers:
        - name: spring-boot-crac
          image: spring-boot-crac:0.0.1
          env:
            - name: VERSION
              value: "v1"
          command: ["/bin/sh","-c", "/app/entrypoint.sh"]
          volumeMounts:
            - mountPath: /crac
              name: crac
          securityContext:
            privileged: true
      volumes:
        - persistentVolumeClaim:
            claimName: crac-store
          name: crac
      restartPolicy: Never
  backoffLimit: 3
