ignite:
  igniteInstanceName: properties-instance-name
  communicationSpi:
    localPort: 5555
  dataStorageConfiguration:
    defaultDataRegionConfiguration:
      initialSize: 10485760 #10MB
    dataRegionConfigurations:
      - name: my-dataregion
        initialSize: 104857600 #100MB
  cacheConfiguration:
    - name: quote
      queryEntities:
        - tableName: QUOTE
          keyFieldName: ID
          keyType: java.lang.Long
          valueType: java.lang.Object
          fields:
            ID: java.lang.Long
            VAL: java.lang.String
    - name: my-cache