---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/commit-id: 54e5a430a2685e2d00391ce7f7acac22dcb49018
    app.quarkus.io/build-timestamp: 2022-12-20 - 07:07:50 +0000
  labels:
    app.kubernetes.io/name: quarkus-reactive-rest
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: quarkus-reactive-rest
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/name: quarkus-reactive-rest
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  type: {{ .Values.app.serviceType }}
