apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticker
spec:
  replicas: {{ .Values.ticker.replicaCount }}
  selector:
    matchLabels:
      app: ticker
  template:
    metadata:
      labels:
        app: ticker
    spec:
      containers:
        - name: ticker
          image: "{{ .Values.ticker.image.repository }}:{{ .Values.ticker.image.version }}"
          ports:
            - containerPort: 8080
          imagePullPolicy: {{ .Values.ticker.image.pullPolicy }}
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "{{ .Values.kafka.bootstrap.service }}.{{ .Values.kafka.namespace }}:{{ .Values.kafka.bootstrap.port }}"
            - name: QUARKUS_HTTP_PORT
              value: "8080"
            - name: AMQP_HOST
              value: "{{ .Values.amqp.host }}"
            - name: AMQP_PORT
              value: "{{ .Values.amqp.port }}"
            - name: AMQP_USERNAME
              value: "{{ .Values.amqp.username }}"
            - name: AMQP_PASSWORD
              value: "{{ .Values.amqp.password }}"
