apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: recommendation
spec:
  host: recommendation
  subsets:
  - labels:
      version: virtualized
    name: version-virtualized
  - labels:
      version: v1
    name: version-v1