apiVersion: "config.istio.io/v1alpha2"
kind: handler
metadata:
  name: handler
spec:
  compiledAdapter: memquota
  params:
    quotas:
    - name: requestcount.quota.istio-system
      # default rate limit is 5000qps
      maxAmount: 5000
      validDuration: 1s
      # The first matching override is applied.
      # A requestcount instance is checked against override dimensions.
      overrides:
      - dimensions:
          destination: recommendation
          destinationVersion: v2
          source: preference
        maxAmount: 1
        validDuration: 1s
