---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/commit-id: 54e5a430a2685e2d00391ce7f7acac22dcb49018
    app.quarkus.io/build-timestamp: 2022-12-20 - 07:07:50 +0000
  labels:
    app.kubernetes.io/name: quarkus-reactive-rest
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: quarkus-reactive-rest
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: quarkus-reactive-rest
      app.kubernetes.io/version: 1.0.0-SNAPSHOT
  template:
    metadata:
      annotations:
        app.quarkus.io/commit-id: 54e5a430a2685e2d00391ce7f7acac22dcb49018
        app.quarkus.io/build-timestamp: 2022-12-20 - 07:07:50 +0000
      labels:
        app.kubernetes.io/name: quarkus-reactive-rest
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: {{ .Values.app.image }}
          imagePullPolicy: IfNotPresent
          name: quarkus-reactive-rest
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
